### ISSUE TITLE
Adjust symlink for Drupal should be outside of the existing_build() function

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/deployments#133]
At the moment the multisite loop causes the symlink for live to be removed and recreated several times (once for each site installed/updated). It should be moved outside of the multisite loop so it happens once.

However, this is tricky because several functions that occur after it use drush aliases to run, which requires the symlink to be correct. So we need to refactor all code using drush aliases so it actually uses `with cd('/path/to/drupal'): drush blah` instead of `drush @alias_name blah` so we can safely process the symlink move later on in the script.

**Comment by gregharvey** [comment]
Same applies for initial_build() and related functions. Should make sure no code there relies on the new symlink being in place as well.

**Comment by EmlynK** [comment]
This is being worked on and is in place in develop. The live symlink is adjusted once all sites have been deployed (i.e if it is a multisite build).

**Comment by EmlynK** [comment]
This has been in place for some time.
