### ISSUE TITLE
Add support for Drush CMI Tools

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/deployments#177]
We can detect the inclusion of Drush CMI Tools in a project as follows:

`drush @site_alias help --format=yaml | grep "config-import-plus"`

If that grep returns results then the Drush module is installed, and if it is installed we can safely assume it should be used and `drush cimy` should be preferred over `drush cim`.

**Comment by EmlynK** [comment]
This duplicates #162. I'll close this one in favour of that one, so have added the description of this ticket on there.
