### ISSUE TITLE
Refactor code relying on drush site aliases

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/deployments#195]
At the moment we check for the existence of a site with a `drush sa` command to list the available sites. However, with drush increasingly shipping with Drupal via composer and that being the desired behaviour for developers, the idea of a system-level drush, thus also system-level drush aliases, is going away.

While we can always install a system drush and figure out a way to enforce its use for alias checks, it will be an oddity in the future. The path of least resistance feels like refactoring this behaviour so it searches for sites based on link existence instead of drush site aliase presence.

**Comment by EmlynK** [comment]
We've not been using Drush aliases for ages now, so closing this issue.
