### ISSUE TITLE
Running phpunit with PHP 5

### ISSUE THREAD

**Issue by opdavies** [codeenigma/deployments#225]
Referring to this code in `common/Tests.py`

```
# We cannot make phpunit work with PHP 5.x, too many problems
# Detect PHP version
php_version = run("php -v | head -1 | awk {'print $2'} | cut -d. -f1,2")
if any(version in php_version for version in [ '5.3', '5.4', '5.5', '5.6' ]):
  # Sorry, PHP too old!
  print "##### Sorry, this version of PHP is too old for current phpunit builds, we cannot run the tests."
  return phpunit_tests_failed
```

What are the issues getting this to run? I've able to do this locally with PHP 5.6 by running a command like `cd www && ../vendor/bin/phpunit -c core modules/custom` and ideally I'd be able to run them during the build to identify and regressions and fail the build automatically if a test fails.

**Comment by gregharvey** [comment]
I can't even remember any more! Lots, as the comment says. Patches welcome, we can give it a try.

**Comment by opdavies** [comment]
Not relevant now anyway as 5.x is EOL.
