### ISSUE TITLE
Drupal settings 'include' should use include, not include_once

### ISSUE THREAD

**Issue by pm98zz-c** [codeenigma/deployments#227]
While not common, it can happen that a static reset 'wipes' some configuration (held in settings.php), and it needs to be re-included.
Typically SimpleSamlPHP integration can break when the idp database settings can't be found.

Switching the 'include_once' to 'include' ensures all settings are always properly loaded, and I can't think of any drawback (the main settings.php is anyway very rarely included more than once).

MR on its way.

**Comment by gregharvey** [comment]
This is being fixed in #229.
