### ISSUE TITLE
'readlink' is not reliable

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/deployments#251]
If someone manually sets the link to not use the full path then this code fails and the script thinks the site does not exist yet, thus triggering a new build:

https://github.com/codeenigma/deployments/blob/9d0d97293b24a2d1adbe7441525b6edc78da3a94/common/Utils.py#L72

Safer to `cd` into the directory and use `pwd` to determine the path.

**Comment by EmlynK** [comment]
This has been fixed and is in the master branch. This issue should have been closed automatically, but looks like it wasn't. \o/
